export const metadata = {
  title: "Admin · Menús",
  description: "Panel interno para preparar menús de Kale Txiki Taberna.",
};

const css = `.adminPage{min-height:100vh;background:#11100f;color:#faf8f3;padding:42px 22px 80px}.adminWrap{max-width:1180px;margin:0 auto}.adminTop{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:42px}.adminBrand{display:flex;align-items:center;gap:16px}.adminBrand img{width:82px;height:auto;filter:invert(1)}.adminBrand span{color:#c9c2b9;font-weight:800}.adminCard{background:#faf8f3;color:#171615;border-radius:28px;padding:28px;box-shadow:0 28px 90px rgba(0,0,0,.32)}.adminGrid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.adminCard h2{font-family:Georgia,serif;font-size:34px;margin:0 0 10px}.adminCard p{color:#706960;line-height:1.6}.field{display:grid;gap:8px;margin-top:18px}.field label{font-weight:900}.field input,.field textarea{border:1px solid rgba(15,15,14,.18);border-radius:16px;padding:13px 14px;font:inherit;background:white}.field textarea{min-height:120px;resize:vertical}.adminNote{margin-top:22px;background:#e7e1d8;border-radius:18px;padding:16px;color:#4f4a45}.adminActions{display:flex;flex-wrap:wrap;gap:10px;margin-top:22px}.adminButton{border:0;border-radius:999px;padding:13px 18px;font-weight:950;background:#11100f;color:#faf8f3}.adminButton.secondary{background:transparent;color:#11100f;border:1px solid rgba(15,15,14,.18)}.adminPreview{margin-top:22px;border:1px dashed rgba(15,15,14,.22);border-radius:20px;padding:18px;background:#fffdf8}.adminPreview strong{display:block;margin-bottom:8px}.adminStatus{margin-top:18px;font-size:14px;color:#706960}@media(max-width:900px){.adminTop{align-items:flex-start;flex-direction:column}.adminGrid{grid-template-columns:1fr}.adminCard{padding:22px}.adminCard h2{font-size:28px}}`;

export default function AdminPage() {
  return <main className="adminPage"><style>{css}</style><div className="adminWrap"><header className="adminTop"><div className="adminBrand"><img src="/logo.png" alt="Kale Txiki" /><div><strong>Panel interno</strong><span>Gestión de menús</span></div></div><a className="adminButton secondary" href="/">Volver a la web</a></header><section className="adminGrid"><article className="adminCard"><h2>Menú del día</h2><p>Prepara el contenido del menú entre semana. Esta pantalla está lista para conectarse a una base de datos y publicar el menú en la web pública.</p><div className="field"><label>Fecha</label><input type="date" /></div><div className="field"><label>Primeros</label><textarea placeholder="Ejemplo: Ensalada mixta\nAlubias\nPasta del día" /></div><div className="field"><label>Segundos</label><textarea placeholder="Ejemplo: Pollo al horno\nMerluza\nHamburguesa" /></div><div className="field"><label>Postre / nota</label><textarea placeholder="Postre, pan, bebida, precio o notas del día" /></div><div className="adminActions"><button className="adminButton">Guardar borrador</button><button className="adminButton secondary">Publicar</button></div><div className="adminStatus">Pendiente de conectar backend y autenticación para guardar cambios reales.</div></article><article className="adminCard"><h2>Fin de semana</h2><p>Espacio para preparar el menú o propuesta especial de sábado/domingo sin tocar código.</p><div className="field"><label>Periodo</label><input placeholder="Ejemplo: Sábado 22 y domingo 23" /></div><div className="field"><label>Propuesta</label><textarea placeholder="Platos, raciones, especialidades o menú de fin de semana" /></div><div className="field"><label>Notas visibles</label><textarea placeholder="Reservas recomendadas, disponibilidad, precio o condiciones" /></div><div className="adminPreview"><strong>Vista previa</strong><p>Cuando conectemos backend, aquí se verá exactamente cómo aparecerá el menú antes de publicarlo.</p></div><div className="adminActions"><button className="adminButton">Guardar borrador</button><button className="adminButton secondary">Publicar fin de semana</button></div></article></section><div className="adminNote">Siguiente paso técnico: crear almacenamiento real para menús y proteger esta ruta con contraseña/login. Sin eso, ningún cambio puede publicarse de forma segura.</div></div></main>;
}
