import { site } from "../lib/site";

const offers = [
  ["Comer al mediodía", "Menú diario y platos de temporada para comer bien entre semana."],
  ["Quedar en la barra", "Pintxos, vermut y ambiente de taberna para tomar algo sin prisa."],
  ["Cenar en cuadrilla", "Raciones, pizzas y hamburguesas para compartir mesa de forma informal."],
  ["Fin de semana", "Comidas con más calma y una propuesta pensada para juntarse."],
];

const pagePolish = `.header{height:74px!important;padding:0 18px 0 22px!important;overflow:hidden!important;align-items:center!important}.logo{height:54px!important;width:134px!important;flex:0 0 134px!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;overflow:hidden!important}.logo img{width:auto!important;height:auto!important;max-width:128px!important;max-height:50px!important;object-fit:contain!important}.nav{align-items:center!important}.hero{padding:112px 22px 38px!important;gap:22px!important;background:#11100f!important;min-height:auto!important}.heroMedia{min-height:calc(100vh - 172px)!important;border-radius:34px!important;box-shadow:0 34px 110px rgba(0,0,0,.32)!important;background-position:center!important}.heroContent{border-radius:34px!important;padding:clamp(44px,6vw,88px)!important;background:linear-gradient(180deg,#fbf7ef,#e9e2d7)!important}.heroBadge{position:absolute;left:28px;bottom:28px;z-index:2;background:rgba(250,248,243,.9);border-radius:999px;padding:12px 18px;font-weight:900;box-shadow:0 18px 60px rgba(0,0,0,.18)}.miniTrust{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:26px}.miniTrust span{border:1px solid rgba(15,15,14,.12);border-radius:18px;padding:14px 16px;background:rgba(255,255,255,.42);font-weight:850}.card{position:relative!important;transition:transform .2s ease,box-shadow .2s ease!important}.card:hover{transform:translateY(-4px)!important;box-shadow:0 26px 80px rgba(15,15,14,.13)!important}.card small{display:block;color:#a4835e;font-weight:950;letter-spacing:.16em;margin-bottom:18px}.reserve{overflow:hidden!important}.reserveCard img{width:auto!important;height:auto!important;max-width:138px!important;max-height:112px!important;object-fit:contain!important}.reserveActions{display:grid;gap:10px}.footer img{width:auto!important;height:auto!important;max-width:145px!important;max-height:118px!important;object-fit:contain!important}.footer p{max-width:330px!important}@media(max-width:980px){.header{height:68px!important;padding-inline:18px!important}.logo{height:48px!important;width:116px!important;flex-basis:116px!important}.logo img{max-width:110px!important;max-height:44px!important}.hero{padding-top:96px!important;grid-template-columns:1fr!important}.heroMedia{min-height:430px!important;order:0!important}.heroContent{order:1!important}.miniTrust{grid-template-columns:1fr}}@media(max-width:640px){.header{top:12px!important;width:calc(100% - 20px)!important}.logo{width:106px!important;flex-basis:106px!important}.logo img{max-width:100px!important;max-height:42px!important}.hero{padding:88px 12px 24px!important}.heroMedia,.heroContent{border-radius:24px!important}.heroMedia{min-height:360px!important}.heroBadge{left:18px;right:18px;bottom:18px;text-align:center}}`;

export default function HomeContentV5() {
  return <main className="site"><style>{pagePolish}</style>
    <header className="header"><a href="#inicio" className="logo" aria-label="Kale Txiki Taberna"><img src="/logo.png" alt="Kale Txiki" /></a><nav className="nav" aria-label="Navegación principal"><a href="#menu">Menús</a><a href="#local">Local</a><a href="#galeria">Ambiente</a><a href="#reservas">Reservas</a></nav><a className="headerCta" href={site.phoneHref}>Reservar</a></header>
    <section className="hero" id="inicio"><div className="heroMedia" aria-label="Interior de Kale Txiki Taberna"><div className="heroBadge">Menú · Vermut · Cenas</div></div><div className="heroContent"><p className="kicker">Lakuntza · Taberna restaurante</p><h1>Comer, tomar algo y cenar en el centro de Lakuntza.</h1><p className="heroLead">Kale Txiki combina menú diario, barra de pintxos, vermut, raciones, pizzas y hamburguesas en un local moderno, cómodo y cercano.</p><div className="heroActions"><a className="btn btnPrimary" href={site.phoneHref}>Reservar por teléfono</a><a className="btn btnSecondary" href={site.mapsUrl} target="_blank" rel="noreferrer">Cómo llegar</a></div><div className="miniTrust"><span>Menú diario</span><span>Barra y vermut</span><span>Cenas informales</span></div><div className="heroMeta"><span>Mikel Arregi Kalea, 3 · Lakuntza</span><span>{site.phone}</span></div></div></section>
    <section className="strip" aria-label="Servicios principales"><div><b>Menú diario</b><span>Comidas de entre semana</span></div><div><b>Fin de semana</b><span>Para venir con calma</span></div><div><b>Barra</b><span>Pintxos y vermut</span></div><div><b>Cenas</b><span>Raciones, pizzas y hamburguesas</span></div></section>
    <section className="section" id="menu"><div className="container"><div className="sectionIntro"><p className="kicker">Qué puedes hacer</p><h2>Una taberna para distintos momentos de la semana.</h2><p>Comer bien al mediodía, quedar en la barra, cenar en cuadrilla o venir el fin de semana sin complicarse.</p></div><div className="cards">{offers.map(([title, text], i) => <article className="card" key={title}><small>{String(i+1).padStart(2,"0")}</small><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="local" id="local"><div className="localImage" /><div className="localCopy"><p className="kicker">El local</p><h2>Un espacio moderno, cálido y fácil de disfrutar.</h2><p>Madera clara, barra negra, tonos piedra y luz cálida. Un local preparado para comer entre semana, juntarse el fin de semana o improvisar una cena sin formalidades.</p></div></section>
    <section className="gallery" id="galeria"><div className="galleryHead"><p className="kicker">Ambiente</p><h2>Taberna de siempre, imagen actual.</h2><p>La web sigue la estética real del local: barra con presencia, comedor cómodo y una atmósfera cuidada sin perder cercanía.</p></div><div className="galleryGrid"><div aria-label="Barra de Kale Txiki" /><div aria-label="Interior del local" /><div aria-label="Comedor de Kale Txiki" /></div></section>
    <section className="reserve" id="reservas"><div><p className="kicker">Reservas y contacto</p><h2>¿Vienes a comer, cenar o tomar algo?</h2><p>Llámanos para consultar disponibilidad, reservar mesa o preguntar por el menú del día.</p></div><aside className="reserveCard"><img src="/logo.png" alt="Kale Txiki" /><a className="phone" href={site.phoneHref}>{site.phone}</a><span>{site.address}</span><div className="reserveActions"><a className="btn btnLight" href={site.phoneHref}>Llamar ahora</a><a className="btn btnLight" href={site.mapsUrl} target="_blank" rel="noreferrer">Abrir en Google Maps</a></div></aside></section>
    <footer className="footer"><div><img src="/logo.png" alt="Kale Txiki" /><p>Bar y restaurante en Lakuntza para comer bien, tomar un vermut, compartir raciones o cenar en un ambiente moderno y cercano.</p></div><div><strong>Contacto</strong><a href={site.phoneHref}>{site.phone}</a><a href={site.mapsUrl} target="_blank" rel="noreferrer">Cómo llegar</a><span>{site.address}</span></div><div><strong>Web</strong><a href="/menu">Menú</a><a href="/reservas">Reservas</a><a href="/contacto">Contacto</a></div><div><strong>Legal</strong><a href="/aviso-legal">Aviso legal</a><a href="/politica-privacidad">Privacidad</a><a href="/politica-cookies">Cookies</a></div></footer>
    <div className="mobileBar"><a href="#menu">Menú</a><a href={site.phoneHref}>Reservar</a><a href={site.mapsUrl}>Llegar</a></div>
  </main>;
}
